
####

POST http://127.0.0.1:8000/main/login/
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "password123"
}


### Login with JWT
POST http://localhost:8000/api/token/
Content-Type: application/json

{
  "username": "sabu",
  "password": "sabu"
}


####
GET  http://localhost:8000/main/products
Content-Type: application/json


    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDE5MTY3LCJpYXQiOjE3NTUwMTg4NjcsImp0aSI6ImY4ZmYzMmExZTU2MTRhNWRhZWFjYTE4ODdmODdlOGRmIiwidXNlcl9pZCI6IjcifQ.MUm_B0wkgAeF3U2c9X9GIlD0UPhRI4FlX-PDMkEp-_c"
